<Project Sdk="Meziantou.NET.Sdk.Test">

  <ItemGroup>
    <PackageReference Include="Meziantou.Framework.TemporaryDirectory" Version="1.0.33" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Meziantou.ShardedTest\Meziantou.ShardedTest.csproj" />
  </ItemGroup>

</Project>