<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolName>sharded-test</ToolName>
    <ToolCommandName>sharded-test</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Meziantou.ShardedTest.Tests" />
  </ItemGroup>

</Project>
